name: build-tag-push

on:
  workflow_dispatch:

jobs:
  build-tag-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Azure Container Registry
        run: |
          echo "${{ secrets.ACR_PASSWORD }}" | docker login acapileacmp2400.azurecr.io \
            --username "${{ secrets.ACR_USERNAME }}" \
            --password-stdin

      - name: Build Docker image
        run: docker build -t final ./ACMP2400

      - name: Tag image
        run: docker tag final acapileacmp2400.azurecr.io/final:latest

      - name: Push image
        run: docker push acapileacmp2400.azurecr.io/final:latest
