name: Build-Curl

on:
  workflow_dispatch:

permissions: {}

jobs:
  build-and-curl:
    runs-on: ubuntu-latest

    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: docker_build
        run: |
          docker build -t pipeline-test .

      - name: docker_run
        run: |
          docker run -d -p 8000:8000 --name test-container pipeline-test

      - name: wait_for_app
        run: |
          sleep 10

      - name: curl_test
        run: |
          curl -f http://localhost:8000/

      - name: Show container logs if needed
        if: failure()
        run: docker logs hello-final-container
